### ISSUE TITLE
C-c,C-b shellExecute failed for local help files

### ISSUE THREAD

**Issue by Jonwyck** [dieter-wilhelm/apdl-mode#14]
**Describe the bug**
I installed the Ansys v211 and APDL-mode. I am trying to use the C-c C-b to look up definition of the command. however, it gave me : "ShellExecute failed: the system cannot find the file specified". Can you tell me how to fix this issue?

windows 10

**Comment by dieter-wilhelm** [comment]
Thank you for the confirmation! :-) Good luck and have fun
