### ISSUE TITLE
stucking after input `/`

### ISSUE THREAD

**Issue by yangdawei** [dieter-wilhelm/apdl-mode#7]
I met a problem that emacs stucks each time after typing `/`. How could I detect the real reason for this problem. Thank you for your response.

**Comment by dieter-wilhelm** [comment]
yangdawei <notifications@github.com> writes:

> I met a problem that emacs stucks each time after typing /. How could I detect the real reason for this problem. Thank you for your response.

In wich major mode does this happen?

Most likely there is something in your init file which is causing this.
Please start Emacs with the -Q option and then load your init code step
by step until you find the offending part.

   Dieter

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>

-- 
Best wishes
H. Dieter Wilhelm
Kelkheim, Germany

**Comment by dieter-wilhelm** [comment]
Can't reproduce this issue
